$ErrorActionPreference = "Stop"

param(
    [string]$PythonExe = "python"
)

Write-Host "=== Building pywallet Windows portable executable ==="

& $PythonExe -m pip install --upgrade pip
& $PythonExe -m pip install pyinstaller bsddb3 ecdsa pycryptodome simplejson

Remove-Item -Recurse -Force build, dist -ErrorAction SilentlyContinue

& $PythonExe -m PyInstaller \
    --noconfirm \
    --clean \
    --onefile \
    --console \
    --name pywallet \
    --hidden-import bsddb3 \
    --hidden-import ecdsa \
    --hidden-import Crypto \
    --hidden-import simplejson \
    pywallet.py

$packageDir = "dist\pywallet-windows-portable"
New-Item -ItemType Directory -Force -Path $packageDir | Out-Null

Copy-Item "dist\pywallet.exe" "$packageDir\pywallet.exe" -Force

@'
@echo off
setlocal

cd /d "%~dp0"

if "%~1"=="" (
  echo Starting pywallet in TUI mode...
  pywallet.exe --tui
) else (
  pywallet.exe %*
)

set "EXIT_CODE=%ERRORLEVEL%"
if not "%EXIT_CODE%"=="0" (
  echo.
  echo pywallet exited with code %EXIT_CODE%.
  pause
)

exit /b %EXIT_CODE%
'@ | Set-Content -Path "$packageDir\run_pywallet_portable.bat" -NoNewline

@'
Portable package generated by build_windows_exe.ps1.

How to use on a PC without Python or WSL:
1) Copy this folder to the target machine.
2) Run run_pywallet_portable.bat
3) Or run pywallet.exe with any pywallet arguments.
'@ | Set-Content -Path "$packageDir\README_PORTABLE.txt" -NoNewline

Write-Host "Build completed. Portable package: $packageDir"
